### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### post 테스트
POST localhost:8080/product/save
Content-Type: application/json
Accept: */*

{
  "name": "product1",
  "description": "nice "
}
